### ISSUE TITLE
wysiwyg styling

### ISSUE THREAD

**Issue by bregtemundo** [Cloudoki/moovly-website#4]
The admins of the site can enter content in a wysiwyg editor (ckeditor). There they can add some basic markup.

One problem is that if you add a basic ul , it isn't styled. (it will only work if you add a class dotted in the ckeditor. and only in an article-view (blog post)

Maybe it is a better idea to put the basic styling of the content (of a content page/ blog/news item)
in a general class (e.g. wysiwyg)

so you get 
.wysiwyg ul {...}
.wysiwyg h2 { ...}

than we can add that class to the right fields, or extend .wysiwyg in our sass

**Comment by bregtemundo** [comment]
Ok for me, keep in mind that in the content pages this will also be needed.
Also, We will want to @extend that class on the element we need

**Comment by Muffles** [comment]
I'm sorry, i don't fully understand your answer. Does that mean it's still not ideal?

**Comment by bregtemundo** [comment]
No, it will be good like that.
Will you also put some styling for table, numbered lists, h3-6, bockquote there.

so when we have another element somewhere that is edited with ck editor. We can put:
.element { @extend .article-view-content; }
and all tags in there will we styled correctly

**Comment by Muffles** [comment]
Pushed.
