### ISSUE TITLE
Regular submenu item example/theming

### ISSUE THREAD

**Issue by GillesVermeulen** [Cloudoki/moovly-website#5]
The only submenu item that is in the templates at the moment, is the specific "Blog" subitems.
Can you also add a normal submenu link? For example "Personal", "Business" and "Education" under the "Solutions" item. I think these should also be available in the mobile menu version.

**Comment by GillesVermeulen** [comment]
Here is an example of how that looks now:
![moovly_submenu_item_issue](https://cloud.githubusercontent.com/assets/2512763/10689940/dfd537ac-797e-11e5-99fe-95002cf3437f.jpg)
(still has the margin-left issue too)

**Comment by Muffles** [comment]
Fixed & pushed on both repos. Added solutions dropdown.
