### ISSUE TITLE
Error in gulpfile.js

### ISSUE THREAD

**Issue by GillesVermeulen** [Cloudoki/moovly-website#7]
The gulpfile says:
dirs.source+'/vendor/imagesLoaded/imagesloaded.pkgd.min.js'

But the actual imagesloaded foldername is not written in camelCase.

**Comment by GillesVermeulen** [comment]
The Solutions template pages (maybe others too) also try to load "<script src="vendor/imagesLoaded/imagesloaded.pkgd.min.js"></script>", but when installed via bower, the folder name is not camelcase.

**Comment by Muffles** [comment]
Fixed & pushed.
